services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api

  api:
    build: ./api
    working_dir: /app
    volumes:
      - ./api:/app
    environment:
      APP_ENV: ${APP_ENV:-local}

      # DB
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fastapi}
      MYSQL_USER: ${MYSQL_USER:-fastapi}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-fastapi}

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redispass}

      # Mailhog (SMTP)
      SMTP_HOST: mailhog
      SMTP_PORT: 1025

    expose:
      - "8000"
    command: >
      bash -lc "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    depends_on:
      - mariadb
      - redis
      - mailhog

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fastapi}
      MYSQL_USER: ${MYSQL_USER:-fastapi}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-fastapi}
    volumes:
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-fastapi}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-fastapi}
      UPLOAD_LIMIT: 128M
    depends_on:
      - mariadb

  redis:
    image: redis:alpine
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD:-redispass}",
        "--maxmemory",
        "${REDIS_MEMORY:-256mb}",
        "--maxmemory-policy",
        "allkeys-lru",
        "--bind",
        "0.0.0.0",
        "--protected-mode",
        "yes"
      ]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
      - REDIS_MEMORY=${REDIS_MEMORY:-256mb}
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mariadb_data:
