version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - sockets:/sockets
    depends_on:
      - apps

  apps:
    build: ./apps
    env_file:
      - .env
    volumes:
      - sockets:/sockets

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    command: ["redis-server","--requirepass","redispass","--maxmemory","256mb","--maxmemory-policy","allkeys-lru"]
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  sockets:
