FROM python:3.12-slim

WORKDIR /apps

RUN apt-get update \
 && apt-get install -y supervisor \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY projects/ /apps/projects/
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-n"]
