[supervisord]
nodaemon=true

[program:test]
directory=/apps/projects/test
command=sh -c "rm -f /sockets/test.sock && uvicorn main:app --uds /sockets/test.sock --uds-permissions 666"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

